---

title: My Cafe
description: Coffee and Tea
author: Me
timezone: Asia/Bangkok
encoding: UTF-8
url: http://jekyll-aws.s3-website-ap-northeast-1.amazonaws.com
meta:
  description: My Cafe in an unknown city
exclude:
  - LICENSE
  - ORIGINAL_README.md
  - package-lock.json
  - package.json
  - gulpfile.js
  - README.md
  - css/flag-icon-css/index.html
permalink: blog/:categories/:year/:month/:day/:title/
plugins:
  - jekyll-archives
  - jekyll-polyglot
  - jekyll-sitemap

highlighter: rouge

# i18n and l10n
languages: ["en", "ja", "th"]
default_lang: "en"
exclude_from_localization:
  - js
  - img
  - css
  - scss
  - node_modules
  - vendor
  - flags
  - favicon.ico
parallel_localization: true

# archives
jekyll-archives:
  enabled:
    - tags
  layout: tag
  permalinks:
    tag: "/blog/tag/:name/"

# GA
project:
  ga_analytics_id: ""
