---

title: My Cafe
description: Coffee and Tea
author: Me
timezone: Asia/Bangkok
encoding: UTF-8
project:
  ga_analytics_id: ""
meta:
  description: My Cafe in an unknown city
exclude:
  - LICENSE
  - ORIGINAL_README.md
  - package-lock.json
  - package.json
  - gulpfile.js
  - README.md
  - css/flag-icon-css/index.html
permalink: blog/:categories/:year/:month/:day/:title/

languages: ["en", "ja", "th"]
default_lang: "en"
exclude_from_localization:
  - js
  - img
  - css
  - scss
  - node_modules
  - vendor
  - flags
  - favicon.ico
parallel_localization: true
